version: "3"
services:
    db:
        image: mysql:8.0.20
        platform: linux/amd64

        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: todo
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            TZ: "Asia/Tokyo"
        command: >
            mysqld --default-authentication-plugin=mysql_native_password

        volumes:
            - ./data/data:/var/lib/mysql

        ports:
            - 3306:3306

    web:
        build: .
        command: python3 todo_project/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db

volumes:
    data:
